server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/message?useSSL=true&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ######
  redis:
    port: 6379
    host: #########
  mail:
    username: #########
    password: ############
    host: smtp.qq.com
  mvc:
    hiddenmethod:
      filter:
        enabled: true
#mybatis-plus:
#
#  type-enums-package: com.poke.Enums

  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
